// <auto-generated />
using System;
using ASP.NET_API_Template.EF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NET_API_Template.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NET_API_Template.Core.Entites.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed@example.com",
                            FullName = "أحمد محمد",
                            IsDeleted = false,
                            PhoneNumber = "1121456789"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@example.com",
                            FullName = "سارة علي",
                            IsDeleted = false,
                            PhoneNumber = "2927654321"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohamed@example.com",
                            FullName = "محمد حسن",
                            IsDeleted = false,
                            PhoneNumber = "31128833445"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "leila@example.com",
                            FullName = "ليلى إبراهيم",
                            IsDeleted = false,
                            PhoneNumber = "4243344556"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali@example.com",
                            FullName = "علي يوسف",
                            IsDeleted = false,
                            PhoneNumber = "0344455667"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima@example.com",
                            FullName = "فاطمة سعيد",
                            IsDeleted = false,
                            PhoneNumber = "5445566778"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khaled@example.com",
                            FullName = "خالد عبد الله",
                            IsDeleted = false,
                            PhoneNumber = "6556677889"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariam@example.com",
                            FullName = "مريم أحمد",
                            IsDeleted = false,
                            PhoneNumber = "7667788990"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef@example.com",
                            FullName = "يوسف علي",
                            IsDeleted = false,
                            PhoneNumber = "0878899001"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nora@example.com",
                            FullName = "نورا محمد",
                            IsDeleted = false,
                            PhoneNumber = "9889900112"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hassan@example.com",
                            FullName = "حسن علي",
                            IsDeleted = false,
                            PhoneNumber = "14490011223"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mona@example.com",
                            FullName = "منى سعيد",
                            IsDeleted = false,
                            PhoneNumber = "01022122334"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar@example.com",
                            FullName = "عمر خالد",
                            IsDeleted = false,
                            PhoneNumber = "01112233445"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "huda@example.com",
                            FullName = "هدى إبراهيم",
                            IsDeleted = false,
                            PhoneNumber = "2223344556"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yasser@example.com",
                            FullName = "ياسر يوسف",
                            IsDeleted = false,
                            PhoneNumber = "03744455667"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nadia@example.com",
                            FullName = "نادية سعيد",
                            IsDeleted = false,
                            PhoneNumber = "0045566778"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "majed@example.com",
                            FullName = "ماجد عبد الله",
                            IsDeleted = false,
                            PhoneNumber = "9956677889"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "salma@example.com",
                            FullName = "سلمى أحمد",
                            IsDeleted = false,
                            PhoneNumber = "0667788990"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ziad@example.com",
                            FullName = "زياد علي",
                            IsDeleted = false,
                            PhoneNumber = "0228899001"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noor@example.com",
                            FullName = "نور محمد",
                            IsDeleted = false,
                            PhoneNumber = "0874900112"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
